[package]
name = "jam"
version = "0.1.0"
authors = ["Javier Pollak <javi.po.123@gmail.com>"]

[dependencies]
jack = "0.5.3"
slog = "2.0.12"
slog-term = "2.2.0"
slog-async = "2.1.0"
sloggers = "0.2.1"
# log = "0.3"
# env_logger = "0.3"
